name = "stashly"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# D1 Database binding for Cloudflare
[[d1_databases]]
binding = "DB"
database_name = "stashly_db"
database_id = "0ca2ffcd-2c31-45b3-ab84-422284173b1d"

# KV Namespace for Next.js Cache & ISR
[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "b5c403e3805143498c436a2e5840e68b"

[vars]
ENVIRONMENT = "production"
